name = "AlignedAllocs"
uuid = "6ac60441-711f-43f0-8178-7f71f0888134"
author = "Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com>"
version = "0.3.0"

[deps]
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
FixedSizeArrays = "1.2.0"
PrecompileTools = "1.2.1"
Test = "1.11"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
